# 配置文件

# 服务端配置
server:
  # 端口设置
  port: 9201

spring:
  # 配置应用信息
  application:
    # 应用名
    name: wechat-ferry
  # swagger适配
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 打成jar包必须添加如下配置才能找到页面
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates

# 日志配置
logging:
  config: classpath:logback-spring.xml

# 本服务参数
wechat:
  ferry:
    # DLL文件位置
    dll-path: E:\WeChatFerry\clients\java\wechat-ferry-mvn\dll\sdk.dll
    # socket端口
    socket-port: 10086
    # 需要开启消息处理的群
    open-msg-groups:
      - 53257911728@chatroom
    # 接收消息转发开关
    receive-msg-fwd-switch: false
    # 接收消息转发URL
    receive-msg-fwd-urls:
      - http://localhost:9001/msg
    # 发送消息转发标识 1-关闭 2-全转发 3-发送成功才转发
    send-msg-fwd-flag: '1'
    # 发送消息转发URL
    send-msg-fwd-urls:
      - http://localhost:9001/msg
    # 调用第三方服务客户端成功状态码
    third-party-ok-codes:
      # key:状态码字段 val:状态码值
      code: '200'

