name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install wcferry
        pip install cffi
        pip install pynng
    
    - name: Build executable
      run: |
        pyinstaller --clean --onefile --hidden-import=cffi --hidden-import=pynng --hidden-import=_cffi_backend wechat_image_monitor.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wechat_image_monitor
        path: dist/wechat_image_monitor.exe 