name: Build EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install wcferry
        
    - name: Build EXE
      run: |
        pyinstaller --onefile --clean wechat_image_monitor.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: WeChatImageMonitor
        path: dist/wechat_image_monitor.exe 