name: Build Windows Executable

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest  # 使用Windows环境
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # 使用Python 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install wcferry grpcio-tools pynng
        
    - name: Build with PyInstaller
      run: |
        cd clients/python
        pyinstaller wcferry.spec --clean --workpath build --distpath dist
        
    - name: Create ZIP archive
      run: |
        cd clients/python/dist
        Compress-Archive -Path WeChatFerry -DestinationPath WeChatFerry-Windows.zip
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: WeChatFerry-Windows
        path: clients/python/dist/WeChatFerry-Windows.zip
        
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
      uses: softprops/action-gh-release@v1
      with:
        files: clients/python/dist/WeChatFerry-Windows.zip
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 