name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller wcferry
    
    - name: Build executable
      run: |
        pyinstaller --clean --onefile wechat_image_monitor.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wechat_image_monitor
        path: dist/wechat_image_monitor.exe 