name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        architecture: 'x64'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install wcferry
        pip install cffi
        pip install pynng
    
    - name: Copy DLL files
      run: |
        python -c "import wcferry; import os; import shutil; wcferry_path = os.path.dirname(wcferry.__file__); shutil.copy(os.path.join(wcferry_path, 'sdk.dll'), '.'); shutil.copy(os.path.join(wcferry_path, 'spy.dll'), '.'); shutil.copy(os.path.join(wcferry_path, 'spy_debug.dll'), '.')"
    
    - name: Build executable
      run: |
        pyinstaller --clean --onefile --add-data "sdk.dll;." --add-data "spy.dll;." --add-data "spy_debug.dll;." --hidden-import=cffi --hidden-import=pynng --hidden-import=_cffi_backend wechat_image_monitor.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wechat_image_monitor
        path: dist/wechat_image_monitor.exe 